services:
  db:
    image: postgres:15
    container_name: balneario-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b41N34r10
      POSTGRES_DB: balneario
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
